org: diegoladrondeg
service: api-comentario

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  timeout: 20
  environment:
    TABLE_NAME: ${self:custom.tableName.${self:provider.stage}}
    INGEST_BUCKET: ${self:custom.ingestBucketName.${self:provider.stage}}
    STAGE: ${self:provider.stage}
  iam:
    role: arn:aws:iam::611279748182:role/LabRole

functions:
  crear:
    handler: comentario.lambda_handler
    events:
      - http:
          path: /comentario/crear
          method: post
          cors: true
          integration: lambda

custom:
  tableName:
    dev: ${self:service}-dev-t_comentarios
    test: ${self:service}-test-t_comentarios
    prod: ${self:service}-prod-t_comentarios

  # dejamos los nombres fijos, sin variables dependientes
  ingestBucketName:
    dev: api-comentario-dev-ingest-alumno
    test: api-comentario-test-ingest-alumno
    prod: api-comentario-prod-ingest-alumno


resources:
  Resources:
    # DynamoDB table (ya estaba en tu yml)
    TablaComentarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName.${self:provider.stage}}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    # Bucket S3 (solo uno, su nombre depende del stage)
    IngestBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.ingestBucketName.${self:provider.stage}}
